# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: envelope.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import request_pb2 as request__pb2
import subscription_pb2 as subscription__pb2
import common_pb2 as common__pb2
import requestV2_pb2 as requestV2__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='envelope.proto',
  package='Application',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x65nvelope.proto\x12\x0b\x41pplication\x1a\rrequest.proto\x1a\x12subscription.proto\x1a\x0c\x63ommon.proto\x1a\x0frequestV2.proto\"\xcd\x02\n\x18\x43lientApplicationMessage\x12?\n\x13\x63lientSingleRequest\x18\x01 \x01(\x0b\x32 .Application.ClientSingleRequestH\x00\x12K\n\x19\x63lientSubscriptionMessage\x18\x02 \x01(\x0b\x32&.Application.ClientSubscriptionMessageH\x00\x12\x43\n\x15\x63lientSingleRequestV2\x18\x03 \x01(\x0b\x32\".Application.ClientSingleRequestV2H\x00\x12O\n\x1b\x63lientSubscriptionMessageV2\x18\x04 \x01(\x0b\x32(.Application.ClientSubscriptionMessageV2H\x00\x42\r\n\x0b\x61pp_message\"\xb6\x04\n\x18ServerApplicationMessage\x12\x41\n\x14serverSingleResponse\x18\x01 \x01(\x0b\x32!.Application.ServerSingleResponseH\x00\x12I\n\x18serverSubscriptionUpdate\x18\x02 \x01(\x0b\x32%.Application.ServerSubscriptionUpdateH\x00\x12M\n\x1aserverSubscriptionResponse\x18\x03 \x01(\x0b\x32\'.Application.ServerSubscriptionResponseH\x00\x12\x45\n\x16serverSubscriptionPing\x18\x04 \x01(\x0b\x32#.Application.ServerSubscriptionPingH\x00\x12\x45\n\x16serverSingleResponseV2\x18\x05 \x01(\x0b\x32#.Application.ServerSingleResponseV2H\x00\x12M\n\x1aserverSubscriptionUpdateV2\x18\x06 \x01(\x0b\x32\'.Application.ServerSubscriptionUpdateV2H\x00\x12Q\n\x1cserverSubscriptionResponseV2\x18\x07 \x01(\x0b\x32).Application.ServerSubscriptionResponseV2H\x00\x42\r\n\x0b\x61pp_message\"\x99\x01\n\x13NotificationMessage\x12<\n\x11\x61lertNotification\x18\x01 \x01(\x0b\x32\x1f.Application.Alert.NotificationH\x00\x12\x35\n\x0egenericMessage\x18\x02 \x01(\x0b\x32\x1b.Application.GenericMessageH\x00\x42\r\n\x0b\x61pp_messageb\x06proto3')
  ,
  dependencies=[request__pb2.DESCRIPTOR,subscription__pb2.DESCRIPTOR,common__pb2.DESCRIPTOR,requestV2__pb2.DESCRIPTOR,])




_CLIENTAPPLICATIONMESSAGE = _descriptor.Descriptor(
  name='ClientApplicationMessage',
  full_name='Application.ClientApplicationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientSingleRequest', full_name='Application.ClientApplicationMessage.clientSingleRequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientSubscriptionMessage', full_name='Application.ClientApplicationMessage.clientSubscriptionMessage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientSingleRequestV2', full_name='Application.ClientApplicationMessage.clientSingleRequestV2', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='clientSubscriptionMessageV2', full_name='Application.ClientApplicationMessage.clientSubscriptionMessageV2', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='app_message', full_name='Application.ClientApplicationMessage.app_message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=98,
  serialized_end=431,
)


_SERVERAPPLICATIONMESSAGE = _descriptor.Descriptor(
  name='ServerApplicationMessage',
  full_name='Application.ServerApplicationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serverSingleResponse', full_name='Application.ServerApplicationMessage.serverSingleResponse', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverSubscriptionUpdate', full_name='Application.ServerApplicationMessage.serverSubscriptionUpdate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverSubscriptionResponse', full_name='Application.ServerApplicationMessage.serverSubscriptionResponse', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverSubscriptionPing', full_name='Application.ServerApplicationMessage.serverSubscriptionPing', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverSingleResponseV2', full_name='Application.ServerApplicationMessage.serverSingleResponseV2', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverSubscriptionUpdateV2', full_name='Application.ServerApplicationMessage.serverSubscriptionUpdateV2', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serverSubscriptionResponseV2', full_name='Application.ServerApplicationMessage.serverSubscriptionResponseV2', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='app_message', full_name='Application.ServerApplicationMessage.app_message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=434,
  serialized_end=1000,
)


_NOTIFICATIONMESSAGE = _descriptor.Descriptor(
  name='NotificationMessage',
  full_name='Application.NotificationMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='alertNotification', full_name='Application.NotificationMessage.alertNotification', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='genericMessage', full_name='Application.NotificationMessage.genericMessage', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='app_message', full_name='Application.NotificationMessage.app_message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=1003,
  serialized_end=1156,
)

_CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSingleRequest'].message_type = request__pb2._CLIENTSINGLEREQUEST
_CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSubscriptionMessage'].message_type = subscription__pb2._CLIENTSUBSCRIPTIONMESSAGE
_CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSingleRequestV2'].message_type = requestV2__pb2._CLIENTSINGLEREQUESTV2
_CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSubscriptionMessageV2'].message_type = requestV2__pb2._CLIENTSUBSCRIPTIONMESSAGEV2
_CLIENTAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSingleRequest'])
_CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSingleRequest'].containing_oneof = _CLIENTAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_CLIENTAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSubscriptionMessage'])
_CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSubscriptionMessage'].containing_oneof = _CLIENTAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_CLIENTAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSingleRequestV2'])
_CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSingleRequestV2'].containing_oneof = _CLIENTAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_CLIENTAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSubscriptionMessageV2'])
_CLIENTAPPLICATIONMESSAGE.fields_by_name['clientSubscriptionMessageV2'].containing_oneof = _CLIENTAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSingleResponse'].message_type = request__pb2._SERVERSINGLERESPONSE
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionUpdate'].message_type = subscription__pb2._SERVERSUBSCRIPTIONUPDATE
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionResponse'].message_type = subscription__pb2._SERVERSUBSCRIPTIONRESPONSE
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionPing'].message_type = subscription__pb2._SERVERSUBSCRIPTIONPING
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSingleResponseV2'].message_type = requestV2__pb2._SERVERSINGLERESPONSEV2
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionUpdateV2'].message_type = requestV2__pb2._SERVERSUBSCRIPTIONUPDATEV2
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionResponseV2'].message_type = requestV2__pb2._SERVERSUBSCRIPTIONRESPONSEV2
_SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _SERVERAPPLICATIONMESSAGE.fields_by_name['serverSingleResponse'])
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSingleResponse'].containing_oneof = _SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionUpdate'])
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionUpdate'].containing_oneof = _SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionResponse'])
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionResponse'].containing_oneof = _SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionPing'])
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionPing'].containing_oneof = _SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _SERVERAPPLICATIONMESSAGE.fields_by_name['serverSingleResponseV2'])
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSingleResponseV2'].containing_oneof = _SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionUpdateV2'])
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionUpdateV2'].containing_oneof = _SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionResponseV2'])
_SERVERAPPLICATIONMESSAGE.fields_by_name['serverSubscriptionResponseV2'].containing_oneof = _SERVERAPPLICATIONMESSAGE.oneofs_by_name['app_message']
_NOTIFICATIONMESSAGE.fields_by_name['alertNotification'].message_type = common__pb2._ALERT_NOTIFICATION
_NOTIFICATIONMESSAGE.fields_by_name['genericMessage'].message_type = common__pb2._GENERICMESSAGE
_NOTIFICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _NOTIFICATIONMESSAGE.fields_by_name['alertNotification'])
_NOTIFICATIONMESSAGE.fields_by_name['alertNotification'].containing_oneof = _NOTIFICATIONMESSAGE.oneofs_by_name['app_message']
_NOTIFICATIONMESSAGE.oneofs_by_name['app_message'].fields.append(
  _NOTIFICATIONMESSAGE.fields_by_name['genericMessage'])
_NOTIFICATIONMESSAGE.fields_by_name['genericMessage'].containing_oneof = _NOTIFICATIONMESSAGE.oneofs_by_name['app_message']
DESCRIPTOR.message_types_by_name['ClientApplicationMessage'] = _CLIENTAPPLICATIONMESSAGE
DESCRIPTOR.message_types_by_name['ServerApplicationMessage'] = _SERVERAPPLICATIONMESSAGE
DESCRIPTOR.message_types_by_name['NotificationMessage'] = _NOTIFICATIONMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientApplicationMessage = _reflection.GeneratedProtocolMessageType('ClientApplicationMessage', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTAPPLICATIONMESSAGE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:Application.ClientApplicationMessage)
  ))
_sym_db.RegisterMessage(ClientApplicationMessage)

ServerApplicationMessage = _reflection.GeneratedProtocolMessageType('ServerApplicationMessage', (_message.Message,), dict(
  DESCRIPTOR = _SERVERAPPLICATIONMESSAGE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:Application.ServerApplicationMessage)
  ))
_sym_db.RegisterMessage(ServerApplicationMessage)

NotificationMessage = _reflection.GeneratedProtocolMessageType('NotificationMessage', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFICATIONMESSAGE,
  __module__ = 'envelope_pb2'
  # @@protoc_insertion_point(class_scope:Application.NotificationMessage)
  ))
_sym_db.RegisterMessage(NotificationMessage)


# @@protoc_insertion_point(module_scope)
